staging: zsmalloc: Fix "map_vm_area" undefined reference errors.
Commit 8addac75a1ab0d8bd5fd25dbbc58e02ddfb089c9 upstream.

This patch adds a MMU dependency to configure the ZSMALLOC in
drivers/staging/zsmalloc/Kconfig. Without this patch, build
system can lead to build failure. This was observed during
randconfig testing, in which ZSMALLOC was enabled w/o MMU being
enabled. Following was the error:

LD      vmlinux
drivers/built-in.o: In function `__zs_map_object':
drivers/staging/zsmalloc/zsmalloc-main.c:650: undefined reference to `map_vm_area'
make: *** [vmlinux] Error 1

Change-Id: Ie20d2d97a5c5e127bb3da04b70839d20c629e9f1
Signed-off-by: Manjunath Goudar <csmanjuvijay@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Reviewed-on: http://review.adnet.avionic-design.de/875
Reviewed-by: Alban Bedel <alban.bedel@avionic-design.de>