thermal: tmp006: Fix a bad format string
A format string is missing a convesion leading to the following warning:

drivers/thermal/tmp006.c: In function 'tmp006_probe':
drivers/thermal/tmp006.c:452:4: warning: too many arguments for format
 [-Wformat-extra-args]

Add the missing conversion to show the error code.

Change-Id: Iad07f0330c48e3c4939382cb17b5fdc6f1e91967
Signed-off-by: Alban Bedel <alban.bedel@avionic-design.de>
Reviewed-on: http://review.adnet.avionic-design.de/6469
Reviewed-by: Dirk Leber <dirk.leber@avionic-design.de>